// All AI Agents organized by category with live simulated metrics
export interface AgentDef {
  id: string;
  name: string;
  category: string;
  categoryColor: string;
  status: 'online' | 'standby' | 'training' | 'offline';
  currentTask: string;
  cpu: number;
  confidence: number;
  speed: string;
  queue: number;
  successRate: number;
  icon: string; // lucide icon name
  description: string;
  integrations: string[];
}

export const AGENT_CATEGORIES = [
  { id: 'all', label: 'All Agents', color: '#06B6D4' },
  { id: 'sales', label: 'Sales & Outreach', color: '#3B82F6' },
  { id: 'leads', label: 'Lead Generation', color: '#10B981' },
  { id: 'content', label: 'Content & Media', color: '#A855F7' },
  { id: 'automation', label: 'Automation', color: '#F59E0B' },
  { id: 'support', label: 'Customer Support', color: '#F43F5E' },
  { id: 'business', label: 'Business Ops', color: '#6366F1' },
  { id: 'advanced', label: 'Advanced AI', color: '#06B6D4' },
];

const r = (min: number, max: number) => Math.floor(Math.random() * (max - min + 1)) + min;

export const ALL_AGENTS: AgentDef[] = [
  // SALES & OUTREACH
  { id: 'support-agent', name: 'Support Agent', category: 'sales', categoryColor: '#3B82F6', status: 'online', currentTask: 'Handling ticket #4821', cpu: r(40,85), confidence: r(88,99), speed: `${r(80,200)}ms`, queue: r(0,12), successRate: r(90,99), icon: 'Headphones', description: 'Resolves customer queries through AI-powered conversations with contextual understanding.', integrations: ['WhatsApp', 'Gmail', 'Supabase'] },
  { id: 'followup-agent', name: 'Follow-up Agent', category: 'sales', categoryColor: '#3B82F6', status: 'online', currentTask: 'Nurturing 34 leads', cpu: r(30,70), confidence: r(85,97), speed: `${r(100,300)}ms`, queue: r(5,30), successRate: r(85,96), icon: 'RefreshCw', description: 'Automates intelligent follow-up sequences based on lead behavior and engagement patterns.', integrations: ['WhatsApp', 'Gmail', 'n8n'] },
  { id: 'automation-sales', name: 'Automation Sales Agent', category: 'sales', categoryColor: '#3B82F6', status: 'online', currentTask: 'Processing pipeline', cpu: r(50,90), confidence: r(90,99), speed: `${r(50,150)}ms`, queue: r(0,8), successRate: r(92,99), icon: 'TrendingUp', description: 'Closes deals autonomously by analyzing prospect intent and delivering personalized pitches.', integrations: ['Stripe', 'OpenAI', 'Supabase'] },
  { id: 'website-sales', name: 'Website Sales Agent', category: 'sales', categoryColor: '#3B82F6', status: 'standby', currentTask: 'Awaiting visitors', cpu: r(5,20), confidence: r(92,99), speed: `${r(30,100)}ms`, queue: 0, successRate: r(88,97), icon: 'Globe', description: 'Engages website visitors in real-time, qualifying leads and booking demos automatically.', integrations: ['OpenAI', 'Stripe', 'Google Maps'] },
  { id: 'whatsapp-outreach', name: 'WhatsApp Outreach Agent', category: 'sales', categoryColor: '#3B82F6', status: 'online', currentTask: 'Sending to 120 contacts', cpu: r(60,95), confidence: r(87,96), speed: `${r(200,500)}ms`, queue: r(20,80), successRate: r(82,94), icon: 'MessageCircle', description: 'Deploys mass WhatsApp outreach campaigns with personalized messaging and smart throttling.', integrations: ['WhatsApp', 'Twilio', 'n8n'] },
  { id: 'instagram-dm', name: 'Instagram DM Agent', category: 'sales', categoryColor: '#3B82F6', status: 'training', currentTask: 'Learning engagement patterns', cpu: r(70,95), confidence: r(75,88), speed: `${r(300,600)}ms`, queue: r(0,5), successRate: r(78,90), icon: 'Instagram', description: 'Automates Instagram DM outreach with contextual replies and story engagement triggers.', integrations: ['Instagram', 'OpenAI'] },
  { id: 'linkedin-outreach', name: 'LinkedIn Outreach Agent', category: 'sales', categoryColor: '#3B82F6', status: 'standby', currentTask: 'Queue empty', cpu: r(2,10), confidence: r(90,98), speed: `${r(100,250)}ms`, queue: 0, successRate: r(85,95), icon: 'Linkedin', description: 'Connects with B2B prospects on LinkedIn with personalized connection requests and follow-ups.', integrations: ['LinkedIn', 'OpenAI', 'Gmail'] },
  { id: 'email-outreach', name: 'Email Outreach Agent', category: 'sales', categoryColor: '#3B82F6', status: 'online', currentTask: 'Sending batch #47', cpu: r(45,80), confidence: r(91,99), speed: `${r(50,150)}ms`, queue: r(10,50), successRate: r(88,97), icon: 'Mail', description: 'Crafts and sends personalized cold emails with AI-optimized subject lines and follow-up chains.', integrations: ['Gmail', 'OpenAI', 'n8n'] },
  { id: 'lead-qualification', name: 'Lead Qualification Agent', category: 'sales', categoryColor: '#3B82F6', status: 'online', currentTask: 'Scoring 89 leads', cpu: r(55,85), confidence: r(93,99), speed: `${r(30,80)}ms`, queue: r(15,60), successRate: r(94,99), icon: 'Filter', description: 'Scores and qualifies inbound leads using multi-dimensional AI analysis and predictive modeling.', integrations: ['Supabase', 'OpenAI', 'Google Maps'] },
  { id: 'cold-calling', name: 'Cold Calling AI Agent', category: 'sales', categoryColor: '#3B82F6', status: 'standby', currentTask: 'Voice model calibrating', cpu: r(10,30), confidence: r(80,92), speed: `${r(500,1000)}ms`, queue: r(0,3), successRate: r(72,88), icon: 'PhoneCall', description: 'Conducts AI-powered cold calls with natural voice synthesis and real-time objection handling.', integrations: ['Twilio', 'OpenAI'] },

  // LEAD GENERATION
  { id: 'google-maps-lead', name: 'Google Maps Lead Agent', category: 'leads', categoryColor: '#10B981', status: 'online', currentTask: 'Scraping Miami dentists', cpu: r(70,95), confidence: r(95,99), speed: `${r(200,400)}ms`, queue: r(30,100), successRate: r(96,99), icon: 'MapPin', description: 'Extracts business leads from Google Maps with contact info, ratings, and enrichment data.', integrations: ['Google Maps', 'Supabase'] },
  { id: 'local-scraper', name: 'Local Business Scraper', category: 'leads', categoryColor: '#10B981', status: 'online', currentTask: 'Processing 450 results', cpu: r(80,98), confidence: r(92,98), speed: `${r(150,350)}ms`, queue: r(50,200), successRate: r(94,99), icon: 'Search', description: 'Discovers local businesses across directories and aggregates contact information at scale.', integrations: ['Google Maps', 'Supabase', 'n8n'] },
  { id: 'b2b-prospect', name: 'B2B Prospect Finder', category: 'leads', categoryColor: '#10B981', status: 'standby', currentTask: 'Awaiting parameters', cpu: r(5,15), confidence: r(90,97), speed: `${r(100,250)}ms`, queue: 0, successRate: r(88,96), icon: 'Building', description: 'Identifies B2B prospects matching your ICP using multi-source intelligence and firmographic data.', integrations: ['LinkedIn', 'OpenAI', 'Supabase'] },
  { id: 'email-extractor', name: 'Email Extractor Agent', category: 'leads', categoryColor: '#10B981', status: 'online', currentTask: 'Extracting from 67 domains', cpu: r(60,90), confidence: r(85,95), speed: `${r(300,600)}ms`, queue: r(20,80), successRate: r(80,93), icon: 'AtSign', description: 'Extracts verified email addresses from websites and public directories with validation.', integrations: ['Gmail', 'Supabase'] },
  { id: 'data-enrichment', name: 'Data Enrichment Agent', category: 'leads', categoryColor: '#10B981', status: 'online', currentTask: 'Enriching 230 records', cpu: r(50,80), confidence: r(88,96), speed: `${r(200,500)}ms`, queue: r(30,120), successRate: r(90,97), icon: 'Layers', description: 'Enriches lead data with social profiles, company info, revenue estimates, and tech stack.', integrations: ['OpenAI', 'Supabase', 'LinkedIn'] },
  { id: 'crm-sync', name: 'CRM Sync Agent', category: 'leads', categoryColor: '#10B981', status: 'online', currentTask: 'Syncing 1.2k records', cpu: r(30,60), confidence: r(97,99), speed: `${r(50,120)}ms`, queue: r(5,30), successRate: r(98,99), icon: 'RefreshCcw', description: 'Bidirectional CRM synchronization keeping your lead database consistent across all platforms.', integrations: ['Supabase', 'n8n', 'Stripe'] },

  // CONTENT & MEDIA
  { id: 'content-creator', name: 'Content Creator Agent', category: 'content', categoryColor: '#A855F7', status: 'online', currentTask: 'Writing blog post #12', cpu: r(60,90), confidence: r(88,96), speed: `${r(500,1200)}ms`, queue: r(3,15), successRate: r(90,97), icon: 'PenTool', description: 'Creates SEO-optimized blog posts, articles, and marketing copy with brand voice consistency.', integrations: ['OpenAI', 'n8n'] },
  { id: 'ai-video', name: 'AI Video Agent', category: 'content', categoryColor: '#A855F7', status: 'training', currentTask: 'Rendering scene #4', cpu: r(85,99), confidence: r(80,92), speed: `${r(2000,5000)}ms`, queue: r(1,5), successRate: r(82,93), icon: 'Video', description: 'Generates short-form video content with AI narration, captions, and dynamic visual effects.', integrations: ['OpenAI'] },
  { id: 'thumbnail-gen', name: 'Thumbnail Generator Agent', category: 'content', categoryColor: '#A855F7', status: 'online', currentTask: 'Generating batch', cpu: r(50,80), confidence: r(90,98), speed: `${r(800,1500)}ms`, queue: r(2,10), successRate: r(92,98), icon: 'Image', description: 'Creates click-optimized thumbnails using AI design principles and A/B testing insights.', integrations: ['OpenAI'] },
  { id: 'social-posting', name: 'Social Media Posting Agent', category: 'content', categoryColor: '#A855F7', status: 'online', currentTask: 'Scheduling 8 posts', cpu: r(20,50), confidence: r(94,99), speed: `${r(100,300)}ms`, queue: r(5,20), successRate: r(96,99), icon: 'Share2', description: 'Schedules and publishes content across all social platforms with optimal timing AI.', integrations: ['Instagram', 'LinkedIn', 'n8n'] },
  { id: 'seo-blog', name: 'SEO Blog Agent', category: 'content', categoryColor: '#A855F7', status: 'online', currentTask: 'Optimizing 3 articles', cpu: r(40,70), confidence: r(91,98), speed: `${r(600,1000)}ms`, queue: r(1,8), successRate: r(89,96), icon: 'FileText', description: 'Writes fully optimized long-form blog content targeting specific keywords and search intent.', integrations: ['OpenAI', 'Google Maps'] },
  { id: 'caption-gen', name: 'Caption Generator Agent', category: 'content', categoryColor: '#A855F7', status: 'standby', currentTask: 'Idle', cpu: r(2,8), confidence: r(93,99), speed: `${r(50,150)}ms`, queue: 0, successRate: r(94,99), icon: 'Type', description: 'Generates engaging social media captions with hashtags, CTAs, and emoji optimization.', integrations: ['OpenAI', 'Instagram'] },

  // AUTOMATION
  { id: 'n8n-workflow', name: 'n8n Workflow Agent', category: 'automation', categoryColor: '#F59E0B', status: 'online', currentTask: 'Running 14 workflows', cpu: r(60,90), confidence: r(95,99), speed: `${r(30,80)}ms`, queue: r(10,40), successRate: r(97,99), icon: 'GitBranch', description: 'Orchestrates complex multi-step workflows across all integrated services and APIs.', integrations: ['n8n', 'Supabase', 'OpenAI'] },
  { id: 'api-integration', name: 'API Integration Agent', category: 'automation', categoryColor: '#F59E0B', status: 'online', currentTask: 'Processing webhooks', cpu: r(40,70), confidence: r(96,99), speed: `${r(20,60)}ms`, queue: r(5,25), successRate: r(98,99), icon: 'Plug', description: 'Manages API connections, handles rate limiting, retries, and data transformation pipelines.', integrations: ['n8n', 'Supabase', 'Stripe'] },
  { id: 'database-auto', name: 'Database Automation Agent', category: 'automation', categoryColor: '#F59E0B', status: 'online', currentTask: 'Optimizing queries', cpu: r(30,60), confidence: r(97,99), speed: `${r(10,40)}ms`, queue: r(2,15), successRate: r(99,99), icon: 'Database', description: 'Automates database operations including migrations, backups, indexing, and query optimization.', integrations: ['Supabase', 'n8n'] },
  { id: 'webhook-manager', name: 'Webhook Manager Agent', category: 'automation', categoryColor: '#F59E0B', status: 'online', currentTask: 'Listening on 8 endpoints', cpu: r(15,40), confidence: r(98,99), speed: `${r(5,20)}ms`, queue: r(0,10), successRate: r(99,99), icon: 'Webhook', description: 'Manages inbound/outbound webhook endpoints with payload validation and retry logic.', integrations: ['n8n', 'Stripe', 'Twilio'] },
  { id: 'ai-scheduler', name: 'AI Scheduler Agent', category: 'automation', categoryColor: '#F59E0B', status: 'online', currentTask: 'Managing 23 jobs', cpu: r(20,45), confidence: r(96,99), speed: `${r(10,30)}ms`, queue: r(5,20), successRate: r(98,99), icon: 'Clock', description: 'Intelligent job scheduling with priority queuing, load balancing, and deadline optimization.', integrations: ['n8n', 'Supabase'] },
  { id: 'cloud-sync', name: 'Cloud Sync Agent', category: 'automation', categoryColor: '#F59E0B', status: 'standby', currentTask: 'Last sync 2m ago', cpu: r(5,15), confidence: r(99,99), speed: `${r(20,50)}ms`, queue: 0, successRate: r(99,99), icon: 'Cloud', description: 'Ensures data consistency across cloud services with conflict resolution and versioning.', integrations: ['Supabase', 'n8n'] },

  // CUSTOMER SUPPORT
  { id: 'ticket-resolver', name: 'Ticket Resolver Agent', category: 'support', categoryColor: '#F43F5E', status: 'online', currentTask: 'Resolving 12 tickets', cpu: r(50,80), confidence: r(88,96), speed: `${r(200,500)}ms`, queue: r(8,30), successRate: r(86,95), icon: 'CheckCircle', description: 'Automatically resolves support tickets by analyzing context and applying known solutions.', integrations: ['Gmail', 'WhatsApp', 'OpenAI'] },
  { id: 'faq-ai', name: 'FAQ AI Agent', category: 'support', categoryColor: '#F43F5E', status: 'online', currentTask: 'Answering queries', cpu: r(30,55), confidence: r(94,99), speed: `${r(50,120)}ms`, queue: r(3,15), successRate: r(95,99), icon: 'HelpCircle', description: 'Provides instant answers to common questions using an AI-powered knowledge base.', integrations: ['OpenAI', 'Supabase'] },
  { id: 'live-chat', name: 'Live Chat Agent', category: 'support', categoryColor: '#F43F5E', status: 'online', currentTask: 'Active in 7 chats', cpu: r(55,85), confidence: r(90,97), speed: `${r(80,200)}ms`, queue: r(2,10), successRate: r(91,98), icon: 'MessageSquare', description: 'Handles live chat conversations with real-time AI responses and seamless human handoff.', integrations: ['WhatsApp', 'OpenAI', 'Twilio'] },
  { id: 'voice-call', name: 'Voice Call Agent', category: 'support', categoryColor: '#F43F5E', status: 'training', currentTask: 'Training voice model', cpu: r(80,98), confidence: r(78,90), speed: `${r(400,800)}ms`, queue: r(0,3), successRate: r(80,92), icon: 'Phone', description: 'Handles inbound voice calls with natural language understanding and voice synthesis.', integrations: ['Twilio', 'OpenAI'] },
  { id: 'review-response', name: 'Review Response Agent', category: 'support', categoryColor: '#F43F5E', status: 'online', currentTask: 'Responding to 5 reviews', cpu: r(25,50), confidence: r(92,98), speed: `${r(300,600)}ms`, queue: r(2,10), successRate: r(93,98), icon: 'Star', description: 'Crafts professional responses to online reviews maintaining brand voice and sentiment.', integrations: ['Google Maps', 'OpenAI'] },

  // BUSINESS OPERATIONS
  { id: 'analytics-agent', name: 'Analytics Agent', category: 'business', categoryColor: '#6366F1', status: 'online', currentTask: 'Processing dashboards', cpu: r(40,70), confidence: r(96,99), speed: `${r(100,300)}ms`, queue: r(1,8), successRate: r(98,99), icon: 'BarChart3', description: 'Generates real-time analytics dashboards with predictive insights and trend detection.', integrations: ['Supabase', 'n8n'] },
  { id: 'reporting-agent', name: 'Reporting Agent', category: 'business', categoryColor: '#6366F1', status: 'online', currentTask: 'Generating weekly report', cpu: r(35,60), confidence: r(95,99), speed: `${r(500,1000)}ms`, queue: r(1,5), successRate: r(97,99), icon: 'FileBarChart', description: 'Creates comprehensive business reports with AI-generated insights and recommendations.', integrations: ['Supabase', 'OpenAI', 'Gmail'] },
  { id: 'finance-assistant', name: 'Finance Assistant Agent', category: 'business', categoryColor: '#6366F1', status: 'standby', currentTask: 'Next billing cycle in 3d', cpu: r(5,15), confidence: r(97,99), speed: `${r(30,80)}ms`, queue: 0, successRate: r(99,99), icon: 'DollarSign', description: 'Manages invoicing, payment tracking, expense categorization, and financial forecasting.', integrations: ['Stripe', 'Supabase'] },
  { id: 'hr-automation', name: 'HR Automation Agent', category: 'business', categoryColor: '#6366F1', status: 'standby', currentTask: 'Idle', cpu: r(2,8), confidence: r(94,98), speed: `${r(100,200)}ms`, queue: 0, successRate: r(96,99), icon: 'Users', description: 'Automates HR workflows including onboarding, scheduling, and employee communication.', integrations: ['Gmail', 'n8n', 'Supabase'] },
  { id: 'project-manager', name: 'Project Manager Agent', category: 'business', categoryColor: '#6366F1', status: 'online', currentTask: 'Tracking 6 sprints', cpu: r(30,55), confidence: r(92,98), speed: `${r(50,120)}ms`, queue: r(3,12), successRate: r(94,98), icon: 'Layout', description: 'Manages project timelines, assigns tasks, tracks milestones, and reports progress autonomously.', integrations: ['n8n', 'Supabase', 'Gmail'] },

  // ADVANCED AI
  { id: 'memory-ai', name: 'Memory AI Agent', category: 'advanced', categoryColor: '#06B6D4', status: 'online', currentTask: 'Indexing 12k memories', cpu: r(50,80), confidence: r(94,99), speed: `${r(20,60)}ms`, queue: r(5,20), successRate: r(97,99), icon: 'Brain', description: 'Manages long-term AI memory storage, retrieval, and contextual association across all agents.', integrations: ['Supabase', 'OpenAI'] },
  { id: 'cognitive-decision', name: 'Cognitive Decision Agent', category: 'advanced', categoryColor: '#06B6D4', status: 'online', currentTask: 'Evaluating 8 decisions', cpu: r(70,95), confidence: r(90,97), speed: `${r(100,300)}ms`, queue: r(3,12), successRate: r(92,98), icon: 'Cpu', description: 'Makes complex business decisions using multi-factor analysis, risk assessment, and pattern recognition.', integrations: ['OpenAI', 'Supabase', 'n8n'] },
  { id: 'ai-research', name: 'AI Research Agent', category: 'advanced', categoryColor: '#06B6D4', status: 'online', currentTask: 'Analyzing market data', cpu: r(60,90), confidence: r(88,96), speed: `${r(500,1500)}ms`, queue: r(2,8), successRate: r(90,97), icon: 'Microscope', description: 'Conducts autonomous research across the web, synthesizing findings into actionable intelligence.', integrations: ['OpenAI', 'Google Maps'] },
  { id: 'autonomous-planning', name: 'Autonomous Planning Agent', category: 'advanced', categoryColor: '#06B6D4', status: 'training', currentTask: 'Learning patterns', cpu: r(75,95), confidence: r(82,93), speed: `${r(200,600)}ms`, queue: r(1,5), successRate: r(85,94), icon: 'Target', description: 'Creates and executes autonomous action plans by decomposing complex goals into subtasks.', integrations: ['OpenAI', 'n8n', 'Supabase'] },
  { id: 'multi-agent-coord', name: 'Multi-Agent Coordinator', category: 'advanced', categoryColor: '#06B6D4', status: 'online', currentTask: 'Orchestrating 12 agents', cpu: r(55,85), confidence: r(95,99), speed: `${r(10,40)}ms`, queue: r(8,30), successRate: r(96,99), icon: 'Network', description: 'Coordinates multiple AI agents for complex workflows, handling dependencies and conflict resolution.', integrations: ['n8n', 'OpenAI', 'Supabase'] },
];
